fix checkMultiple handling of permissions with type on iOS
zoontek/react-native-permissions pull request #136
Opened 2017-09-02 17:46 UTC by erezrokah

Related to this:
https://github.com/yonahforst/react-native-permissions/issues/133

This is just a bug fix.
If we want to support passing 'types' to `checkMultiple` I think a different pr is required (and discussed since it can be implemented a few ways).

2017-09-07 08:38 UTC, eosterberg commented
this skould be merged immediately, bumped into the same bug and ended up with the exact same fix!

2017-09-18 21:57 UTC, th317erd commented
Please merge this PR... I have also run into this issue.

2017-09-26 22:02 UTC, yonahforst requested changes

2017-09-26 22:02 UTC, yonahforst commented on index.ios.js
> +		type = type || DEFAULTS[permission]
I don't think this line is necessary. The default is handled in the objc code.

2017-09-26 22:04 UTC, yonahforst commented
@erezrokah - thanks so much for this PR. And great spot with the index bug! have a look at my comment on line 43. If you remove that line, I'll merge this ASAP

2017-09-28 08:30 UTC, erezrokah commented
@yonahforst done :) Thanks!

2017-09-28 08:30 UTC, yonahforst approved these changes

2017-09-28 08:30 UTC, merged

2017-09-28 08:30 UTC, yonahforst commented
thanks @erezrokah!!