feat(android): add schedule exact alarm permission
zoontek/react-native-permissions pull request #878
Opened 2024-06-03 20:43 UTC by seyedmostafahasani

# Summary
I managed the new permission for scheduling exact alarms in Android 13 and higher.

## Test Plan
I added this permission to the sample app.

### What's required for testing (prerequisites)?

### What are the steps to test it (after prerequisites)?

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅    |

## Checklist

- [*] I have tested this on a device and a simulator
- [*] I added the documentation in `README.md`
- [*] I added a sample use of the API in the example project (`example/App.tsx`)

2024-06-06 20:16 UTC, zoontek approved these changes, later dismissed

2024-06-06 20:16 UTC, zoontek commented on android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java
> +    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
There's no need for this extra check. If the permission is not available in the manifest, it will return `false`

2024-06-06 20:16 UTC, zoontek commented on android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java
> +        if (context.getSystemService(AlarmManager.class).canScheduleExactAlarms()) {
Unfortunately, this approach does not work with `checkMultiple`

2024-06-06 20:16 UTC, zoontek commented on android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java
> +        if (context.getSystemService(AlarmManager.class).canScheduleExactAlarms()) {
Same, it doesn't work with `requestMultiple`

2024-06-06 20:18 UTC, zoontek requested changes
`checkMultiple` / `requestMultiple` support must be added

2024-06-07 08:26 UTC, seyedmostafahasani commented
> `checkMultiple` / `requestMultiple` support must be added

I handled schedule exact alarm with both functions.

2024-06-20 09:13 UTC, kevynb commented
Hello @zoontek, anything we could do to help this PR be merged?

We also need the feature and I was wondering if we could provide additional support to speed things up.

2024-06-20 10:43 UTC, zoontek commented
Not really, I'm in a middle of packing / selling all my stuff because I'm moving soon.

I will probably have a bit more bandwidth next week.

2024-06-20 13:48 UTC, Zhigamovsky commented
I think the function to open a specific Alarm settings could be added as well.

2024-06-20 14:50 UTC, seyedmostafahasani commented
@zoontek If you have any suggestions, I am available to apply them.

2024-07-11 08:37 UTC, ThomasReyskens commented
I just tried the code. When requesting permission, it opens up a list, displaying all apps. To create a better UX, I would add `intent.setData(Uri.fromParts("package", reactContext.getPackageName(), null));` at line 215 of the `RNPermissionsModuleImpl.java`.

patch: 
```diff --git a/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java b/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java
index 97bc712..cda5f87 100644
--- a/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java
+++ b/node_modules/react-native-permissions/android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java
@@ -2,6 +2,7 @@ package com.zoontek.rnpermissions;
 
 import android.Manifest;
 import android.app.Activity;
+import android.app.AlarmManager;
 import android.content.Context;
 import android.content.Intent;
 import android.content.pm.PackageManager;
@@ -12,11 +13,13 @@ import android.provider.Settings;
 import android.util.SparseArray;
 
 import androidx.annotation.NonNull;
+import androidx.annotation.RequiresApi;
 import androidx.core.app.NotificationManagerCompat;
 
 import com.facebook.common.logging.FLog;
 import com.facebook.react.bridge.Arguments;
 import com.facebook.react.bridge.Callback;
+import com.facebook.react.bridge.LifecycleEventListener;
 import com.facebook.react.bridge.Promise;
 import com.facebook.react.bridge.ReactApplicationContext;
 import com.facebook.react.bridge.ReadableArray;
@@ -27,6 +30,7 @@ import com.facebook.react.modules.core.PermissionListener;
 
 import java.util.ArrayList;
 import java.util.HashMap;
+import java.util.HashSet;
 import java.util.Map;
 
 public class RNPermissionsModuleImpl {
@@ -47,6 +51,9 @@ public class RNPermissionsModuleImpl {
   }
 
   private static boolean isPermissionUnavailable(@NonNull final String permission) {
+    if (Manifest.permission.SCHEDULE_EXACT_ALARM.equals(permission)) {
+      return false;
+    }
     String fieldName = permission
       .replace("android.permission.", "")
       .replace("com.android.voicemail.permission.", "");
@@ -113,6 +120,17 @@ public class RNPermissionsModuleImpl {
       return;
     }
 
+    if (Manifest.permission.SCHEDULE_EXACT_ALARM.equals(permission)) {
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+        if (context.getSystemService(AlarmManager.class).canScheduleExactAlarms()) {
+          promise.resolve(GRANTED);
+        } else {
+          promise.resolve(DENIED);
+        }
+        return;
+      }
+    }
+
     if (context.checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED) {
       promise.resolve(GRANTED);
     } else {
@@ -147,6 +165,14 @@ public class RNPermissionsModuleImpl {
             == PackageManager.PERMISSION_GRANTED
             ? GRANTED
             : BLOCKED);
+      } else if (Manifest.permission.SCHEDULE_EXACT_ALARM.equals(permission)) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+          if (context.getSystemService(AlarmManager.class).canScheduleExactAlarms()) {
+            output.putString(permission, GRANTED);
+          } else {
+            output.putString(permission, DENIED);
+          }
+        }
       } else if (context.checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED) {
         output.putString(permission, GRANTED);
       } else {
@@ -179,6 +205,42 @@ public class RNPermissionsModuleImpl {
       return;
     }
 
+    if (Manifest.permission.SCHEDULE_EXACT_ALARM.equals(permission)) {
+      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+        if (context.getSystemService(AlarmManager.class).canScheduleExactAlarms()) {
+            promise.resolve(GRANTED);
+        } else {
+          try {
+            Intent intent = new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM);
+            intent.setData(Uri.fromParts("package", reactContext.getPackageName(), null));
+            reactContext.startActivity(intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));
+            // Register a lifecycle listener to check permission status when app resumes
+            reactContext.addLifecycleEventListener(new LifecycleEventListener() {
+              @Override
+              public void onHostResume() {
+                // Check the permission status when the app resumes
+                if (context.getSystemService(AlarmManager.class).canScheduleExactAlarms()) {
+                  promise.resolve(GRANTED);
+                } else {
+                  promise.resolve(DENIED);
+                }
+                reactContext.removeLifecycleEventListener(this);
+              }
+
+              @Override
+              public void onHostPause() {}
+
+              @Override
+              public void onHostDestroy() {}
+            });
+          } catch (Exception e) {
+            promise.reject(ERROR_INVALID_ACTIVITY, e);
+          }
+        }
+        return;
+      }
+    }
+
     if (context.checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED) {
       promise.resolve(GRANTED);
       return;
@@ -222,6 +284,7 @@ public class RNPermissionsModuleImpl {
     promise.resolve(getLegacyNotificationsResponse(reactContext, BLOCKED));
   }
 
+  @RequiresApi(api = Build.VERSION_CODES.S)
   public static void requestMultiple(
     final ReactApplicationContext reactContext,
     final PermissionListener listener,
@@ -230,8 +293,8 @@ public class RNPermissionsModuleImpl {
     final Promise promise
   ) {
     final WritableMap output = new WritableNativeMap();
-    final ArrayList<String> permissionsToCheck = new ArrayList<String>();
-    int checkedPermissionsCount = 0;
+    final ArrayList<String> permissionsToCheck = new ArrayList<>();
+    final HashSet<String> pendingPermissions = new HashSet<>();
     Context context = reactContext.getBaseContext();
 
     for (int i = 0; i < permissions.size(); i++) {
@@ -239,7 +302,6 @@ public class RNPermissionsModuleImpl {
 
       if (isPermissionUnavailable(permission)) {
         output.putString(permission, UNAVAILABLE);
-        checkedPermissionsCount++;
       } else if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
         output.putString(
           permission,
@@ -247,17 +309,24 @@ public class RNPermissionsModuleImpl {
             == PackageManager.PERMISSION_GRANTED
             ? GRANTED
             : BLOCKED);
-
-        checkedPermissionsCount++;
+      } else if (Manifest.permission.SCHEDULE_EXACT_ALARM.equals(permission)) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+          if (context.getSystemService(AlarmManager.class).canScheduleExactAlarms()) {
+            output.putString(permission, GRANTED);
+          } else {
+            permissionsToCheck.add(permission);
+            pendingPermissions.add(permission);
+          }
+        }
       } else if (context.checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED) {
         output.putString(permission, GRANTED);
-        checkedPermissionsCount++;
       } else {
         permissionsToCheck.add(permission);
+        pendingPermissions.add(permission);
       }
     }
 
-    if (permissions.size() == checkedPermissionsCount) {
+    if (pendingPermissions.isEmpty()) {
       promise.resolve(output);
       return;
     }
@@ -276,18 +345,49 @@ public class RNPermissionsModuleImpl {
             for (int j = 0; j < permissionsToCheck.size(); j++) {
               String permission = permissionsToCheck.get(j);
 
-              if (results.length > 0 && results[j] == PackageManager.PERMISSION_GRANTED) {
-                output.putString(permission, GRANTED);
+              if (Manifest.permission.SCHEDULE_EXACT_ALARM.equals(permission)) {
+                reactContext.addLifecycleEventListener(new LifecycleEventListener() {
+                  @Override
+                  public void onHostR [...]

2024-07-11 08:41 UTC, seyedmostafahasani commented
@ThomasReyskens it is a good idea.
I will add it to the code.

2024-07-28 19:34 UTC, seyedmostafahasani commented
@zoontek if you have enough time, please check out my PR. I think a lot of people would like to use this feature. I am available to apply any suggestions you may have.

2024-09-02 09:31 UTC, zoontek requested changes

2024-09-02 09:31 UTC, zoontek commented on android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java
> +    if (Manifest.permission.SCHEDULE_EXACT_ALARM.equals(permission)) {
The permission is not available below Android 12, so this check is incorrect.

2024-09-02 09:31 UTC, zoontek commented on android/src/main/java/com/zoontek/rnpermissions/RNPermissionsModuleImpl.java
> +  @RequiresApi(api = Build.VERSION_CODES.S)
Why has this been added? The method must stay usable on Android below S

2024-10-16 13:00 UTC, ezwaydev commented
Excuse me, how was this merged ? I do not see any of this functionality in https://github.com/zoontek/react-native-permissions/commit/d253fb0285c789f1b8036543a67ae1f43a87b696 (v5.0.0)

2024-10-16 13:45 UTC, zoontek commented
@ezwaydev It has been automatically closed by Github as https://github.com/zoontek/react-native-permissions/pull/890 has been merged and contains `closes …`, but you are right, it's not merged.

2024-10-19 02:20 UTC, seyedmostafahasani commented
@zoontek 
I resolved conflicts.

2024-10-28 08:33 UTC, seyedmostafahasani commented
@zoontek 
Would you please review my PR?

2024-10-28 09:17 UTC, zoontek commented
@seyedmostafahasani It's on my TODO, but please **stop** pressuring maintainers. I'm currently working a lot on [react-native-edge-to-edge](https://github.com/zoontek/react-native-edge-to-edge) and helping debugging new architecture issues, this comes just after.

2024-10-29 23:36 UTC, zoontek commented
Closed in favor of https://github.com/zoontek/react-native-permissions/pull/905, which is available in [5.1.0](https://github.com/zoontek/react-native-permissions/releases/tag/5.1.0)

2024-10-29 23:36 UTC, closed without merging